# Generated by Django 2.2.16 on 2020-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201101_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='users/%Y/%m/%d/'),
        ),
    ]
